// This code is generated by NRestGen v1.0.0.
// Any changes to this file will be overwritten when regenerated.
// Generated at 2020-09-17 14:35:41
using MediatR;
using Microsoft.AspNet.OData.Extensions;
using NRestGen.Web.ResourceModel;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace NRestGen.Web
{
    public static class StartupExtensions
    {
        public static IServiceCollection AddNRestGen(this IServiceCollection services)
        {
            services.AddMediatR(typeof(Startup).Assembly);
            services.AddOData();
            return services;
        }

        public static IEndpointRouteBuilder AddNRestGen(this IEndpointRouteBuilder endpoints)
        {
            var resourceModel = ResourceModelBuilder.Build();
            endpoints.MapODataRoute("OData", "api", resourceModel);
            endpoints.EnableDependencyInjection();
            return endpoints
                .Select()
                .Filter()
                .Count()
                .MaxTop(100)
                ;
        }
    }
}
