// This code is generated by NRestGen v1.0.0.
// Any changes to this file will be overwritten when regenerated.
// Generated at 2020-09-14 14:31:30
using NRestGen;
using System;
using System.Collections.Generic;

namespace NRestGen.Web.ResourceModel
{
    public partial class Customer : Entity
    {
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public IEnumerable<Order> Orders { get; set; }
    }

    public partial class Order : Entity
    {
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public IEnumerable<OrderLine> OrderLines { get; set; }
    }

    public partial class OrderLine : Entity
    {
        public int OrderId { get; set; }
        public int OrderLineId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
    }

}
