// This code is generated by RestGen v1.0.0.
// Any changes to this file will be overwritten when regenerated.
// Generated at 2020-08-24 11:17:01
using MediatR;
using Microsoft.AspNet.OData;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using NRestGen.Web.ResourceModel;

namespace NRestGen.Web.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public partial class OrderLinesController : ODataController //ControllerBase
    {
        private readonly IMediator _mediator;

        public OrderLinesController(IMediator mediator)
        {
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
        }

        [HttpHeadGet("{id?}")]
        [EnableQuery]
        public async Task<ActionResult<IQueryable<OrderLine>>> Get(int? id = null)
        {
            var request = new GetRequest<OrderLine>(id.GetValueOrDefault());
            var response = await _mediator.Send(request);
            return Ok(response.Collection.AsQueryable());
        }
    }
}
