// This code is generated by NRestGen v1.0.0.
// Any changes to this file will be overwritten when regenerated.
// Generated at 2020-09-14 14:41:06
using MediatR;
using Microsoft.AspNet.OData;
using Microsoft.AspNet.OData.Query;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using NRestGen.Web.ResourceModel;

namespace NRestGen.Web.Controllers
{
    /// <summary>
    /// Handles resource requests for the OrderLine type.
    /// </summary>
    [ApiController]
    [ApiVersion("1")]
    //[Route("api/v{v:apiVersion}/[controller]")]
    [Route("api/[controller]")]
    public partial class OrderLinesController : ControllerBase
    {
        private readonly IMediator _mediator;

        public OrderLinesController(IMediator mediator)
        {
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
        }

        [HttpHeadGet("{id?}")]
        public async Task<IActionResult> Get(CancellationToken cancellationToken, ODataQueryOptions<OrderLine> options, int? id = null)
        {
            var request = new GetRequest<OrderLine>(options, id.GetValueOrDefault())
            {
                Context = NewRequestContext()
            };
            var response = await _mediator.Send(request, cancellationToken);
            return Ok(response);
        }

        private RequestContext NewRequestContext()
        {
            return new RequestContext(Request.Method, Request.Path, Request.QueryString.Value);
        }
    }
}
