// This code is generated by NRestGen v1.0.0.
// Any changes to this file will be overwritten when regenerated.
// Generated at 2020-08-27 15:40:22
using Microsoft.AspNet.OData;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using NRestGen.Web.ResourceModel;

namespace NRestGen.Web.Controllers
{
    [ApiController]
    [ApiVersion("1")]
    //[Route("api/v{v:apiVersion}/[controller]")]
    [Route("api/[controller]")]
    public partial class OrdersController : ControllerBase
    {

        [HttpHeadGet("{id?}")]
        public async Task<ActionResult<IQueryable<Order>>> Get(int? id = null)
        {
            var request = new Request<Order>(id.GetValueOrDefault());
            var response = await Handle(request);
            return Ok(response.Collection.AsQueryable());
        }
        
        [HttpHeadGet("{id}/OrderLines")]
        public async Task<IActionResult> GetOrderLines(int id)
        {
            var request = new Request<OrderLine>()
            {
                ParentId = new ResourceIdentifier(typeof(Order), id)
            };
            var response = await Handle(request);
            return Ok(response.Collection);
        }
    }
}
